# Show colors in console output (and log files)
color-logs: true

# Debug output to console (and log files)
debug-mode: false

# Language file (for translations)
language-file: lang-en.yml

# Give a key to the first player that joins after server starts up
first-key-on-join: "example"
