name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Bukkit Plugin
author: BillyGalbreath

commands:
    pl3xcrates:
        description: "§2Admin plugin commands"
        usage: |-
               §e/crate (reload|set|remove|givekey) (crate) (player) (amount)
               §6Ex§7: §e/crate §7- §3View version information.
               §6Ex§7: §e/crate reload §7- §3Reloads the plugin crates and configs.
               §6Ex§7: §e/crate set example §7- §3Sets the target block as crate.
               §6Ex§7: §e/crate remove example §7- §3Removes the target block as crate.
               §6Ex§7: §e/crate givekey example billy §7- §3Gives billy a key for example crate.
               §6Ex§7: §e/crate givekey example billy 3 §7- §3Gives billy 3 keys for example crate.
               §6Ex§7: §e/crate givekey example all 3 §7- §3Gives all online users 3 keys for example crate.
        aliases:
        - cr
        - crate
        - crates

permissions:
    pl3xcrates.use:
        description: Allows to use/open crates
        default: true
    pl3xcrates.givekey:
        description: Allows to give crate keys to players
        default: op
    pl3xcrates.set:
        description: Allows to set crates in world
        default: op
    pl3xcrates.remove:
        description: Allows to remove crates from world
        default: op
    pl3xcrates.reload:
        description: Allows to reload the plugin
        default: op

    pl3xcrates.admin:
        description: Allows to administer plugin
        default: op
        children:
            pl3xcrates.givekey: true
            pl3xcrates.set: true
            pl3xcrates.remove: true
            pl3xcrates.reload: true
