name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Bukkit Plugin"
author: "BillyGalbreath"
api-version: "1.13"
softdepend:
  - HolographicDisplays

commands:
  crates:
    description: "§2Admin plugin commands"
    usage: |-
      §e/crates (reload|set|remove|givekey) (crate) (player) (amount)
      §6Ex§7: §e/crates §7- §3View version information.
      §6Ex§7: §e/crates reload §7- §3Reloads the plugin crates and configs.
      §6Ex§7: §e/crates set example §7- §3Sets the target block as crate.
      §6Ex§7: §e/crates remove example §7- §3Removes the target block as crate.
      §6Ex§7: §e/crates givekey example billy §7- §3Gives billy a key for example crate.
      §6Ex§7: §e/crates givekey example billy 3 §7- §3Gives billy 3 keys for example crate.
      §6Ex§7: §e/crates givekey example all 3 §7- §3Gives all online users 3 keys for example crate.

permissions:
  crates.use:
    description: Allows to use/open crates
    default: true
  crates.givekey:
    description: Allows to give crate keys to players
    default: op
  crates.set:
    description: Allows to set crates in world
    default: op
  crates.remove:
    description: Allows to remove crates from world
    default: op
  crates.reload:
    description: Allows to reload the plugin
    default: op
  crates.blacklist:
    description: Control the first-join blacklist
    default: op

  crates.admin:
    description: Allows to administer plugin
    default: op
    children:
      crates.givekey: true
      crates.set: true
      crates.remove: true
      crates.reload: true
      crates.blacklist: true
